#ifndef MYSTICSQUARE_MAINWINDOW_HH
#define MYSTICSQUARE_MAINWINDOW_HH

#include <QMainWindow>


QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

/**
 * The main window for Mystic Square.
 *
 * Contains the game area and the main controls.
 */
class MainWindow : public QMainWindow {
Q_OBJECT

public:
    /**
     * Create a new MainWindow.
     * @param parent The parent of the newly created window.
     */
    explicit MainWindow(QWidget *parent = nullptr);

    ~MainWindow() override;

public slots:
    /**
     * Show the "About Mystic Square" dialog.
     */
    void aboutApp();

    /**
     * Show the "About Qt" dialog.
     */
    void aboutQt();

    /**
     * Show the "New Game" dialog.
     */
    void newGame();

    /**
     * Show the "Load Game" dialog.
     */
    void loadGame();

    /**
     * Show the "Save Game" dialog.
     */
    void saveGame();

private:
    /**
     * The UI code generated by Qt Designer.
     */
    Ui::MainWindow *ui;
};


#endif //MYSTICSQUARE_MAINWINDOW_HH
