#ifndef MYSTICSQUARE_NEWGAMEDIALOG_HH
#define MYSTICSQUARE_NEWGAMEDIALOG_HH

#include <QDialog>

QT_BEGIN_NAMESPACE
namespace Ui { class NewGameDialog; }
QT_END_NAMESPACE

/**
 * The new game dialog.
 *
 * Displays a QSpinBox to let the user choose the size of the game.
 */
class NewGameDialog : public QDialog {
Q_OBJECT

public:
    /**
     * Create a new NewGameDialog.
     * @param parent The parent of this dialog.
     */
    explicit NewGameDialog(QWidget *parent = nullptr);

    /**
     * Get the value selected by the user.
     * @return
     */
    [[nodiscard]] int getValue() const;

    ~NewGameDialog() override;

private:
    /**
     * The UI code generated by Qt Designer.
     */
    Ui::NewGameDialog *ui;
};


#endif //MYSTICSQUARE_NEWGAMEDIALOG_HH
